# Generated by Django 5.2.17 on 2026-09-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunityresponse',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
