# Generated by Django 6.1 on 2026-08-16 08:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, default='✨', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('skills', models.JSONField(blank=True, default=list)),
                ('experience_years', models.PositiveIntegerField(default=5)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('location', models.CharField(blank=True, default='Chennai, TN', max_length=255)),
                ('latitude', models.FloatField(default=13.0827)),
                ('longitude', models.FloatField(default=80.2707)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('completed_jobs_count', models.PositiveIntegerField(default=12)),
                ('is_verified', models.BooleanField(default=True)),
                ('trust_score', models.PositiveIntegerField(default=95)),
                ('skill_passport', models.JSONField(blank=True, default=dict)),
                ('skill_passport_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating', '-trust_score'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=10)),
                ('image_url', models.TextField(blank=True, default='')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='marketplace.category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='marketplace.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pricing_unit', models.CharField(default='per service', max_length=50)),
                ('duration', models.CharField(blank=True, default='1-2 hours', max_length=50)),
                ('image_url', models.TextField(blank=True, default='')),
                ('languages', models.JSONField(blank=True, default=list)),
                ('is_available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='marketplace.category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='marketplace.providerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
